services:
  web:
    #build: ./frontend/
    image: ghcr.io/seanmorley15/adventurelog-frontend:latest
    container_name: adventurelog-frontend
    restart: unless-stopped
    environment:
      - PUBLIC_SERVER_URL=http://server:80 # Should be the service name of the backend with port 80, as that's what the backend container exposes
      - ORIGIN=http://localhost:8020
      - BODY_SIZE_LIMIT=Infinity
    ports:
      - "8020:3000"
    depends_on:
      - server

  db:
    image: tobi312/rpi-postgresql-postgis:15-3.3-alpine-arm
    container_name: adventurelog-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: adventure
      POSTGRES_PASSWORD: changeme123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    #build: ./backend/
    image: ghcr.io/seanmorley15/adventurelog-backend:latest
    container_name: adventurelog-backend
    restart: unless-stopped
    environment:
      - PGHOST=db
      - PGDATABASE=database
      - PGUSER=adventure
      - PGPASSWORD=changeme123
      - SECRET_KEY=changeme123
      - DJANGO_ADMIN_USERNAME=admin
      - DJANGO_ADMIN_PASSWORD=admin
      - DJANGO_ADMIN_EMAIL=admin@example.com
      - PUBLIC_URL=https://adventurelogserver.misharubanov.com:8021 # Match the outward port, used for the creation of image urls
      - CSRF_TRUSTED_ORIGINS=
          http://localhost,
          https://localhost,
          http://adventurelogserver.misharubanov.com,
          https://adventurelogserver.misharubanov.com,
          http://adventurelog.misharubanov.com,
          https://adventurelog.misharubanov.com  # Comma separated list of trusted origins for CSRF
      - ALLOWED_HOSTS=localhost,adventurelogserver.misharubanov.com,adventurelog.misharubanov.com
      - DEBUG=False
      - FRONTEND_URL=https://adventurelog.misharubanov.com:8020 # Used for email generation. This should be the url of the frontend
    ports:
      - "8021:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media:/code/media/

volumes:
  postgres_data:
  adventurelog_media: