services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver:stable
    volumes:
      - 'lms-config:/config:rw'
      - /mnt/storagebox/lyrion/music:/music:ro
      - /mnt/storagebox/lyrion/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    environment:
      - HTTP_PORT=9000
      - HTTP_INTERFACE=0.0.0.0
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
