services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver:latest
    volumes:
      - /mnt/storagebox/lyrion/config:/config:rw
      - /mnt/storagebox/lyrion/music:/music:ro
      - /mnt/storagebox/lyrion/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    network_mode: host
    environment:
      - HTTP_PORT=9000
      - PUID=1000
      - PGID=1000
    restart: unless-stopped