services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver:latest
    volumes:
      - /mnt/storagebox/lyrion/config:/config:rw
      - /mnt/storagebox/lyrion/music:/music:ro
      - /mnt/storagebox/lyrion/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 9000:9000/tcp
      - 9090:9090/tcp
      - 3483:3483/tcp
      - 3483:3483/udp
    environment:
      - HTTP_PORT=9000
    restart: unless-stopped