services:
  lms:
    container_name: lms
    image: lmscommunity/lyrionmusicserver:stable
    volumes:
      - /mnt/storagebox/lyrion/config:/config:rw
      - /mnt/storagebox/lyrion/music:/music:ro
      - /mnt/storagebox/lyrion/playlist:/playlist:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - HTTP_PORT=9000
      - PUID=1000
      - PGID=1000
    command: >
      sh -c "chown -R 1000:1000 /config && chmod -R 755 /config && /lms/slimserver.pl"
    restart: unless-stopped